[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
template_anchor = "FiifvSGXR8Q8BPCKTremuAkVXxuUefLGbhtw781kER1N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/manhtb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
